---
title: "Final Project"
author: "Anwesha Guha, Heidi Iwashita, Chris Loan, Adam Nielsen & Aaron Rothbart"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    highlight: espresso
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}
library(tidyverse)
library(janitor)
library(rio)
library(here)
theme_set(theme_minimal())
```

```{r data import}
grad <- import(here("data", "2005-2010__Graduation_Outcomes_-__By_Borough.csv"))
grad <- grad %>% 
  clean_names() %>% 
  as_tibble()
grad
```
The data we are starting with are already tidy, but for the purposes of demonstrating our rather acute proficiency in our _ability_ to tidy data, in this segment will make the data untidy and then tidy it once more.

```{r exploring data}

summary(grad$cohort) # needs to be cleaned in new df, change Aug 2006 to 2006

clean_grad <- grad
clean_grad$cohort <-  as.numeric(sub("Aug 2006", "2006", grad$cohort))

clean_grad

messy_grad <- clean_grad %>% 
  pivot_wider(names_from = borough,
              values_from = total_cohort)
clean_grad_2 <- messy_grad %>% 
  pivot_longer(cols = c("Bronx":"Staten Island"),
               names_to = "borough",
               values_to = "total_cohort",
               values_drop_na = TRUE)

clean_grad_2 <- clean_grad_2[, c(1,21,2,22,3:20)]
```

```{r}
clean_grad %>% 
  filter(demographic == "English Language Learners" | 
           demographic == "English Proficient Students") %>% 
  mutate(`English Language Learner Status` = 
           factor(demographic, 
                  levels = c("English Language Learners", 
                      "English Proficient Students"), 
                  labels = c('Learner', 'Proficient')
                  )
         ) %>% group_by(`English Language Learner Status`, borough) %>% 
  ggplot(aes(x = `English Language Learner Status`, 
             y = total_grads_percent_of_cohort)) +
  geom_jitter(aes(color = cohort)) + facet_wrap(~borough) + 
  labs(title = 'Figure 1. Graduation Rates in NYC by English Learner Status',
       subtitle = 'Boroughs are reported separetely with lighter dots indicating more recent years',
       y = 'Percent of Total Cohort')
```

